# ── RAMSES-RT on the Iliev Test-1 problem (ADR-0006 Phase 4, flagship 2 core) ─
#
# The SAME physical setup as Enzo's PhotonTest, expressed as a generated
# mini-ramses namelist: hydrogen-only gas at n_H = 1e-3 cm⁻³ held isothermal at
# 1e4 K (`neq_TConst`), a 5e48 photons/s monochromatic 13.6 eV point source in
# the corner of a 6.6 kpc box, gas frozen (`static_gas`).  Where Moray traces
# adaptive rays at infinite signal speed, RAMSES-RT advects an M1 photon fluid
# at a REDUCED speed of light — two genuinely different RT methods on one
# density field, which is exactly what the Phase-4 cross-check gate wants.
#
# Units: kpc–m_p–Myr (`UNITS_PARAMS`), so code time is Myr and code density is
# H/cc — the same numbers PhotonTest uses.

function ramsesrt_iliev_namelist(; level::Integer, c_fraction::Real,
                                 nH::Real = 1e-3, Ndot::Real = 5e48,
                                 boxlen_kpc::Real = 6.6)
    return """
    Iliev Test 1 (generated by MultiCode.jl — ADR-0006 Phase 4)

    &RUN_PARAMS
    hydro=.true.
    rt=.true.
    static_gas=.true.
    ncontrol=1
    nrestart=0
    nremap=0
    nsubcycle=10*1
    nstepmax=100000
    nsuperoct=2
    verbose=.false.
    /

    &AMR_PARAMS
    levelmin=$(level)
    levelmax=$(level)
    ngridtot=3000000
    ncachemax=30000
    nexpand=1
    boxlen=$(boxlen_kpc)
    /

    &INIT_PARAMS
    nregion=1
    region_type(1)='square'
    x_center=$(boxlen_kpc / 2)
    y_center=$(boxlen_kpc / 2)
    z_center=$(boxlen_kpc / 2)
    length_x=100.0
    length_y=100.0
    length_z=100.0
    exp_region=10.0
    d_region=$(nH)
    u_region=0.0
    v_region=0.0
    w_region=0.0
    p_region=$(8.69869e-5 * nH)
    /

    &OUTPUT_PARAMS
    foutput=0
    tout=100000.0
    /

    &HYDRO_PARAMS
    gamma=1.4
    courant_factor=0.8
    slope_type=1
    riemann='hllc'
    /

    &UNITS_PARAMS
    units_length=3.09d21
    units_density=1.66000d-24
    units_time=3.1556926d13
    /

    &COOLING_PARAMS
    neq_chem=.true.
    isHe=.false.
    isH2=.false.
    X_H=1.0
    Y_He=0.0
    neq_TConst=1d4
    is_init_xion=.true.
    /

    &REFINE_PARAMS
    interpol_var=0
    interpol_type=0
    /

    &RT_PARAMS
    rt_advect=.true.
    rt_c_fraction=$(c_fraction)
    rt_nsubcycle=500
    rt_otsa=.true.
    /

    &RT_SOURCES
    rt_nsource=1
    rt_source_type=1*'point'
    rt_src_x_center=$(boxlen_kpc / 2^(level + 1))
    rt_src_y_center=$(boxlen_kpc / 2^(level + 1))
    rt_src_z_center=$(boxlen_kpc / 2^(level + 1))
    rt_src_length_x=0.0
    rt_src_length_y=0.0
    rt_src_length_z=0.0
    rt_src_group=1
    rt_n_source=$(Ndot)
    rt_u_source=0.0
    rt_v_source=0.0
    rt_w_source=0.0
    /

    &RT_GROUPS
    group_csn(1,:)=6.30d-18
    group_cse(1,:)=6.30d-18
    group_egy=13.60001
    /
    """
end

"""
    ramsesrt_set_density!(h, lev, den::AbstractArray{<:Real,3}; nH=1e-3, lib=:rt)

Inject a density FIELD (n³ box-ordered, in units of the reference density —
e.g. an Enzo host's code-unit density) into a uniform RAMSES level: var 1
becomes `nH·den` (RAMSES code density = H/cc here), and the density-weighted
passives ride along — the ionization fraction xHII (var 6) and the total
energy (var 5, ∝ ρ at the pinned temperature) are scaled by the local ratio,
so the chemical state stays consistent.  The cross-code coupling point of
ADR-0006 flagship 2.
"""
function ramsesrt_set_density!(h::RamsesLib.Handle, lev::Integer,
                               den::AbstractArray{<:Real,3};
                               nH::Real = 1e-3, lib::Symbol = :rt)
    n1d = 2^lev
    size(den) == (n1d, n1d, n1d) ||
        error("ramsesrt_set_density!: field must be $(n1d)³, got $(size(den))")
    ck, U = RamsesLib.get_hydro_all(h, :uold, lev; lib = lib)
    noct = size(ck, 1)
    nv = size(U, 3)
    new = [Matrix{Float64}(undef, noct, 8) for _ in 1:nv]
    @inbounds for o in 1:noct, c in 1:8
        i = 2 * ck[o, 1] + ((c - 1) & 1) + 1
        j = 2 * ck[o, 2] + ((c - 1) >> 1 & 1) + 1
        k = 2 * ck[o, 3] + ((c - 1) >> 2 & 1) + 1
        ρnew = nH * den[i, j, k]
        ratio = ρnew / U[o, c, 1]
        new[1][o, c] = ρnew
        for v in 2:4
            new[v][o, c] = U[o, c, v] * ratio        # momenta (zero for static gas)
        end
        new[5][o, c] = U[o, c, 5] * ratio            # E ∝ ρ at pinned temperature
        for v in 6:nv
            new[v][o, c] = U[o, c, v] * ratio        # density-weighted passives (xHII·ρ)
        end
    end
    for v in 1:nv
        RamsesLib.set_hydro!(h, :uold, v, lev, ck, new[v]; lib = lib)
    end
    return nothing
end

"Raster a uniform RAMSES level's xHII = uold₆/uold₁ onto a box-ordered n³ array."
function ramsesrt_xhii_grid(h::RamsesLib.Handle, lev::Integer; lib::Symbol = :rt)
    ck, xr = RamsesLib.get_hydro(h, :uold, 6, lev; lib = lib)
    _, ρ = RamsesLib.get_hydro(h, :uold, 1, lev; lib = lib)
    n1d = 2^lev
    out = Array{Float64,3}(undef, n1d, n1d, n1d)
    @inbounds for o in 1:size(ck, 1), c in 1:8
        i = 2 * ck[o, 1] + ((c - 1) & 1) + 1
        j = 2 * ck[o, 2] + ((c - 1) >> 1 & 1) + 1
        k = 2 * ck[o, 3] + ((c - 1) >> 2 & 1) + 1
        out[i, j, k] = xr[o, c] / ρ[o, c]
    end
    return out
end

"I-front radius [box units] from a RAMSES-RT level: spherical x_HII profile about the corner."
function ramsesrt_ifront_radius(h; lev, lib = :rt)
    # ion passive scalars are stored DENSITY-WEIGHTED (uold₆ = xHII·ρ)
    ck, xr = RamsesLib.get_hydro(h, :uold, 6, lev; lib = lib)  # xHII·ρ (NION=1)
    _, ρ = RamsesLib.get_hydro(h, :uold, 1, lev; lib = lib)
    x = xr ./ ρ
    noct = size(ck, 1)
    n1d = 2^lev
    dx = 1.0 / n1d
    nb = 2 * n1d
    sums = zeros(nb); counts = zeros(Int, nb)
    @inbounds for o in 1:noct, c in 1:8
        r = 0.0
        for d in 1:3
            bit = (c - 1) >> (d - 1) & 1
            xc = (2 * ck[o, d] + bit + 0.5) * dx
            r += xc^2
        end
        r = sqrt(r)
        b = min(nb, 1 + floor(Int, r / (dx / 2)))
        sums[b] += x[o, c]; counts[b] += 1
    end
    rb = [(b - 0.5) * dx / 2 for b in 1:nb]
    xb = [counts[b] > 0 ? sums[b] / counts[b] : NaN for b in 1:nb]
    r_I = NaN
    for b in 2:nb
        (isnan(xb[b - 1]) || isnan(xb[b])) && continue
        if xb[b - 1] >= 0.5 > xb[b]
            f = (xb[b - 1] - 0.5) / (xb[b - 1] - xb[b])
            r_I = rb[b - 1] + f * (rb[b] - rb[b - 1])
            break
        end
    end
    return (r_I = r_I, r = rb, xHII = xb)
end

"""
    run_ramsesrt_stromgren(; t_end_myr=5.0, snapshots=[3.0,5.0], level=6,
                           c_fraction=0.005, dt_myr=0.25)
        -> (; history, t, diag)

RAMSES-RT on the Iliev Test-1 field: generated namelist (units = Myr/kpc/mp),
gas frozen, the Julia driver owning the clock — each outer step sets
`g%dtnew` and runs `rt_setup! → rt_step!` (which subcycles the M1 solve +
photo-chemistry at the reduced-c CFL).  Returns the I-front history
[(t_myr, r_I_box)] at the `snapshots` epochs.

`c_fraction` trades front fidelity (early fronts lag when v_front ≳ 0.1·c_red)
against periodic wrap time (photons re-enter after boxlen/c_red ≈ 4.3 Myr at
0.005) — keep the comparison epochs inside the clean window.
"""
function run_ramsesrt_stromgren(; t_end_myr::Real = 5.0, snapshots = [3.0, 5.0],
                                level::Integer = 6, c_fraction::Real = 0.005,
                                dt_myr::Real = 0.25, lib::Symbol = :rt)
    CodeBridge.available(RamsesLib.BRIDGE, lib) ||
        error("RAMSES RT library not found (build bin64hrt or set RAMSES_LIB_RT)")
    dir = mktempdir()
    write(joinpath(dir, "iliev1.nml"),
          ramsesrt_iliev_namelist(; level = level, c_fraction = c_fraction))
    snaps = sort(unique(vcat(Float64.(snapshots), Float64(t_end_myr))))
    return cd(dir) do
        h = RamsesLib.init("iliev1.nml"; lib = lib)
        RamsesLib.nrtvar(; lib = lib) >= 4 ||
            error("loaded RAMSES library has no RT state (nrtvar=$(RamsesLib.nrtvar(lib=lib)))")
        lev = RamsesLib.info(h; lib = lib).levelmin
        RamsesLib.rt_neq_updates!(h, 0; lib = lib)   # fill the σ·c chemistry tables
        t = 0.0; n = 0
        history = Tuple{Float64,Float64}[]
        for target in snaps
            while t < target * (1 - 1e-12) && n < 100_000
                dt = min(Float64(dt_myr), target - t)
                RamsesLib.set_dt!(h, lev, dt; lib = lib)
                RamsesLib.rt_setup!(h, lev; lib = lib)
                RamsesLib.rt_step!(h, lev; lib = lib)
                t += dt; n += 1
            end
            push!(history, (t, ramsesrt_ifront_radius(h; lev = lev, lib = lib).r_I))
        end
        return (history = history, t = t, diag = (steps = n, level = lev, c_fraction = c_fraction),
                handle = h, free = () -> RamsesLib.finalize(h; lib = lib))
    end
end
