"""Regression test for Enzo initial conditions against golden signatures.

For each committed ``fixtures/Problems/*.json``, re-initialize the
corresponding problem (via Enzo's InitializeNew, wrapped by
``enzomodules.problems.Problem``), recompute its signature, and assert it
matches the stored one within a tight floating tolerance.

Skips cleanly when the grid solver library is not built.  Fixtures are
generated by ``tools/capture_problems.py``.
"""
import glob
import json
import os

import pytest

from enzomodules import problems
from enzomodules.problem_signature import signature, compare_signatures

# <repo>/EnzoModules/tests/test_problem_fixtures.py
#   dirname -> EnzoModules/tests ; ../.. -> repo root
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ENZOMODULES = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FIXTURE_DIR = os.path.join(ENZOMODULES, "fixtures", "Problems")

RTOL = 1e-10
ATOL = 1e-300

FIXTURES = sorted(glob.glob(os.path.join(FIXTURE_DIR, "*.json")))


pytestmark = pytest.mark.skipif(
    not problems.available(),
    reason="grid solver library not built; run EnzoModules/deps/build_grid.sh")


def test_repo_layout():
    """Sanity: REPO computed from the test location really is the repo root."""
    assert os.path.isdir(os.path.join(REPO, "run")), \
        f"run/ not found under computed REPO={REPO}"


@pytest.mark.skipif(not FIXTURES, reason="no problem signature fixtures captured")
@pytest.mark.parametrize("fixture_path", FIXTURES,
                         ids=[os.path.basename(p) for p in FIXTURES])
def test_problem_signature_matches(fixture_path):
    with open(fixture_path) as fh:
        stored = json.load(fh)

    rel = stored["paramfile"]
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        pytest.skip(f"parameter file missing: {rel}")

    with problems.Problem(path) as p:
        fresh = signature(p)

    ok, msg = compare_signatures(stored, fresh, rtol=RTOL, atol=ATOL)
    assert ok, f"{os.path.basename(fixture_path)}: {msg}"
